annisadevikegiatan/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from .views import kegiatan, formorang, bacakegiatan

app_name = 'main'

urlpatterns = [
    path('', kegiatan, name='kegiatan'),
    path('formorang', formorang, name='formorang'),
    path ('bacakegiatan', bacakegiatan, name="bacakegiatan"),
]

main/models.py
from django.db import models

# Create your models here.
class Kegiatan(models.Model):
    namaKegiatan = models.CharField(max_length=30)
    
class Orang(models.Model):
    namaOrang = models.CharField(max_length=30)
    kegiatanOrang = models.ForeignKey(Kegiatan, on_delete=models.CASCADE, default=0)

main/forms.py
from django import forms
from .models import Kegiatan, Orang

class Input_Form(forms.ModelForm):
        class Meta:
            model = Kegiatan
            fields = ['namaKegiatan']

        error_messages={
            'required' : 'Please Type'
        }

        kegiatan_attrs = {
            'type' : 'text',
            'class' : 'form-control',
            'placeholder' : 'Tidur'
        }

        namaKegiatan = forms.CharField(label='Nama Kegiatan', required=True, max_length=30, widget=forms.TextInput(attrs=kegiatan_attrs))


class Input_Form_Orang(forms.ModelForm):
        class Meta:
            model = Orang
            fields = ['namaOrang', 'kegiatanOrang']

        error_messages={
            'required' : 'Please Type'
        }

        orang_attrs = {
            'type' : 'text',
            'class' : 'form-control',
            'placeholder' : 'Pewe'
        }

        namaOrang = forms.CharField(label='Nama Orang:', required=True, max_length=30, widget=forms.TextInput(attrs=orang_attrs))
        
    

main/views.py
from django.shortcuts import render, redirect
from .models import Kegiatan, Orang
from .forms import Input_Form, Input_Form_Orang

response = {}
def kegiatan(request):
    form = Input_Form(request.POST or None)
    if request.method=="POST" and form.is_valid:
        form.save()
        return redirect('/bacakegiatan')
    else:
        form = Input_Form()
        response['form'] = form

        kegiatan=Kegiatan.objects.all()
        response['kegiatan'] = kegiatan

        orang = Orang.objects.all()
        response['orang'] = orang

        return render(request, 'main/kegiatan.html', response)

def bacakegiatan(request):
    return redirect('/')


def formorang(request):
    form2 = Input_Form_Orang(request.POST or None)
    if request.method=="POST" and form2.is_valid:
        form2.save()
        return redirect('/bacakegiatan')
    else:
        form2 = Input_Form_Orang()
        response['form2'] = form2
        return render(request, 'main/formorang.html', response)

main/templates/main/formorang.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="{% static 'static/css/style.css' %}"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    {%block style%}
    {%endblock style%}
    <title> Formulir </title>
</head>

{%block content%}

<body>
    <section id="formorang">
        <form action="formorang" method="POST">
          {% csrf_token %}
          <div class="form-group">
              {{form2.as_p}}
          </div>
            <button class="btn btn-primary intabel" method="POST">Submit</button>
        </form>
    
      </section>
</body>

{%endblock content%}
</html>

main/templates/main/kegiatan.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="{% static 'static/css/style.css' %}"> -->
    {%block style%}
    {%endblock style%}
    <title> Pilih Kegiatan </title>
</head>

{%block content%}

<body>
  <section id="formkegiatan">
    <form action="/" method="POST">
      {% csrf_token %}
      <div class="form-group">
          {{form.as_p}}
      </div>
      <button type="submit" value="Submit" class="btn btn-primary">Submit</button>
    </form>

  </section>
  <section id="kegiatan">
    <div class="row">
      {%if kegiatan%}
          {%for k in kegiatan%}
            <div class="col-sm-6">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">{{k.namaKegiatan}}</h5>
                  {%if orang%}
                    {%for o in orang%}
                      {%if o.kegiatanOrang == k %}
                        <p class="card-text">{{o.namaOrang}}</p>
                      {%endif%}
                    {%endfor%}
                  {%endif%}
                    <a href="{% url 'main:formorang' %}"> 
                      <button class="btn btn-primary intabel">Tambah Peserta</button>
                    </a>
                </div>
              </div>
            </div>
          {%endfor%}
      {%endif%}
      </div>
  </section>
</body>

{%endblock content%}
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block style %}
  {% endblock style %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>